"""add to favorites

Revision ID: 85f59f932dd7
Revises: 75631189ca63
Create Date: 2024-07-21 23:08:41.407850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f59f932dd7'
down_revision = '75631189ca63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_firstname', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_firstname', ['firstname'])

    # ### end Alembic commands ###
